name: LINT CI
on:
  push:
    paths:
      - "./demos/**"
      - ".github/workflows/demos-ci.yml"

defaults:
  run:
    working-directory: ./demos

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: ./demos/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run linter
        shell: bash
        run: npm run lint
